// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240121000739_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Data.Entities.PostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author1",
                            Comment = "Comment1",
                            Content = "Content1",
                            Date = new DateTime(2000, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tags = "Sport"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author2",
                            Comment = "Comment2",
                            Content = "Content2",
                            Date = new DateTime(2001, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tags = "Sport"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author3",
                            Comment = "Comment3",
                            Content = "Content3",
                            Date = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tags = "Tech"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author4",
                            Comment = "Comment4",
                            Content = "Content4",
                            Date = new DateTime(2002, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tags = "Health"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author5",
                            Comment = "Comment5",
                            Content = "Content5",
                            Date = new DateTime(2013, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tags = "New"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
